title: Setup Guides
email: yannick.weber@haw-landshut.de
description: A collection of guides to ease the setup of your tools for my lectures. PRs welcome!
github_username:  acidsepp
theme: minima
header_pages:
  - index.markdown
